[package]
name = "bevy_sandbox"
version = "0.3.0"
authors = ["Adam Aposhian <aposhian.dev@gmail.com>"]
edition = "2021"

[dependencies]
bevy = "0.18"
avian2d = "0.5"
bevy_prototype_lyon = "0.16"
bevy_ecs_tilemap = "0.18"
pathfinding = "4"
tiled = "0.15"
serde_json = "1"
